monkey = [
   {"sticker_id": "CAACAgIAAxkBAAELniBl6DIjS1auRFVjKyM6SfxAxKleRQACGyIAAkVMSUmXt8Y5yAscFjQE", "text": "Ти патеряный бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELniZl6DJeodKfiKWsJu_bV819kU3zkwACeiIAAuhleUqy3MrR92oAAfQ0BA", "text": "Ти глустный бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELni5l6DJ6uGA7NMfbV0KkgQLaFfnWjQAC1SIAAjrw-EuqVhe4O4uNEzQE", "text": "Ти улыбаящаийся бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnkBl6DLImQGeLx12KKApJFEWaDEq8AACvS0AAhKmaUrJ-5JseSWYlTQE", "text": "Ти депресинвий бибизян((9"},
   {"sticker_id": "CAACAgIAAxkBAAELnkJl6DLnbgrEDTjx41l7V67Kf6-XswACoRoAAjNr8UlRn7snL37A0jQE", "text": "Ти бибизян ни панимающий длугих бибизянов "},
   {"sticker_id": "CAACAgIAAxkBAAELnkRl6DMLQTFCUB1fx00jxRIqUJfKSgACDCEAAvKkyUhwuUsR4bLTSTQE", "text": "Ти сомнитильный бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnpRl6DOhPDDrU-H6LOZTNQG_khRNKQACfDQAAimUeUirAWQcA4zZ3TQE", "text": "Ти хлопащий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnpZl6DPAKWW5q0VKQFy4BGiu1QjvdQAC-iwAAqgygEjNFzhtezefmTQE", "text": "Ти свэг бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnphl6DPeuN7m1VJHqhCErISd77RwTQAC-jUAAjBSgUjNaFImcwZS5DQE", "text": "Ти любапитнии бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnppl6DRIwcR67Fqpt-4-exai6fhGAwACKzAAAnJwcEnxyqhKm9ojLjQE", "text": "Ти въетманский флешбек бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnpxl6DRl39KZQTTg5JXdB2xrXAuQ_wACRBgAAt_v6UnnVUwXPPz3DzQE", "text": "Ти гламурьний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnp5l6DR9okPXvgpOESzDD7cPMSDiEwACCyYAAqeoYUhwLdKW5xMmtDQE", "text": "Ти злой-злой-злой бибизян!!"},
   {"sticker_id": "CAACAgIAAxkBAAELnqBl6DTsBjpXlYNUt3ALDXI6HWmPbQACnS0AArg1SUk4l-5erVNphzQE", "text": "Ти уставсий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnqJl6DUQPvnYEe1Tip0soDWtnJbWJAACxxoAAg6YyEgo6dHZN84sJzQE", "text": "Ти хитрий улыбака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnqRl6DUrbAesQDmIChUbmUS95nXpsAACciMAAuwtwUuTZ5fNpe9RXjQE", "text": "Ти согласний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnqZl6DVA9OjI8QH-q2YZhJwzeYLjRwAChzMAAmD6GEgoArYefI_K7jQE", "text": "Ти осинь хитлий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnqhl6DVZkjvvHmqF4btSXNKF-FGTQwACszcAAtdZsUsJzT4arLrO5DQE", "text": "Ти намикаюсий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnqpl6DV1S09HXB-63gTtcfNyDaH_swAC6TUAAmZ9-EsoeWurDHTc6DQE", "text": "Ти самий испальнитильний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnqxl6DWq0GYlp1ewSVV6Z_t99cE06wACkzEAAq00sEstuXiJH438NjQE", "text": "Ти задумсивий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnq5l6DXdUC0dmf2PRHAusVHuW1UhUgAC2iEAAiWlSUm8mW8BjBRTlzQE", "text": "Ти малинький адинокий бибизян(("},
   {"sticker_id": "CAACAgIAAxkBAAELnrBl6DYbcw3w2kFGRDY8ysUh-CYx4QACQCIAAnq2YEur-eo2cza__jQE", "text": "Ти клутой бибизян! "},
   {"sticker_id": "CAACAgIAAxkBAAELnrJl6DYvKxT7y6LciGFQUGaXP2Zr9AACUC4AAvThcElsGKXVJtZ0CjQE", "text": "Ти спалтивний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnrRl6DZFh1TJ4YR6sJ2-7ctRNssRvQACLDEAAjzqaUqpM3a491bVyjQE", "text": "Ти многа кушац бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnsZl6DamFYYz5dGN9BxxvtG2FidqHQACrzIAAt20sEuPeIdh_Lp1LTQE", "text": "Ти нерьвний срив бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnspl6Dc0x_JwKS_eX-i4f7IE04i_bwACqRgAAiN14EmbOFoIHL1lSzQE", "text": "Ти очаловатильний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELns5l6DeFW3amZ0-oi54hvGGUtWN0ggAC5iwAAtQv-Ep66A_GBPiNGjQE", "text": "Ти сонний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnuxl6DenZkOIfsnCkjI2BgcFZmpypQACMS0AApCw-UqwLZ4LHxawSTQE", "text": "Ти бибизян интлаверть"},
   {"sticker_id": "CAACAgIAAxkBAAELnxpl6DfjngWv2D7CZJeXKJsgmdBf3wACVykAAgO4-Eqlw-4UKbodNjQE", "text": "Ти шокилований бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELny5l6DgNd6R2Uc_26NIiWAp9GeP9mQACOSEAAoVJ-UoqY_AkcRGk-zQE", "text": "Ти легиндарний бибизян, ти заслузил пахвалу бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnzBl6Dg2e1zjqn-NHXNCai_8rJSUhgACFjAAAl_78Urw_59JiqqmsDQE", "text": "Ти абнимашьки бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnzJl6DhSsBqZzhXiSHytlzRQdmXFjAACRSwAAoEAAflKgktjwaXBkRs0BA", "text": "Ти безлаботний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnzRl6Dhxodf7EQ6ZLTcplBtrnoKv3QACUiwAAqty8Eo8gUx5BptcwDQE", "text": "Ты балтовать бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnzZl6DiqhxTKf0YVG-wbn4TV77Ww0QAC7isAAqL9-ErqxnPXK3Zj9zQE", "text": "Ти думаюсий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnzhl6Dj4nvsCAACAgIAAxkBAAELnzhl6Dj4nvsf24omxgl7s848OK38LAACpiwAAlFq-Ep-boqUoPKJATQEf24omxgl7s848OK38LAACpiwAAlFq-Ep-boqUoPKJATQE", "text": "Ти look lonely бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnzpl6DnXQgzojPWBi2KJjZGuDvy7_QACihUAAmYG6EuTCy_G1yF0mTQE", "text": "Ти на стиле бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELnzxl6DnwD3jSeIl4s79dDrkbYliftAACUhYAAigq6Usq1xeds4OgkjQE", "text": "Ти пятницний муд бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELnz5l6Doe7wLCTC1_YsROWyHyJBLWRwAC6RkAAjiZ8UsdJdNVK40hITQE", "text": "Ти не пон бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0Bl6DozQHixKzWlqAGVmIm9r5QOOwAC2hIAAiuc8UuioTfV9M_vJzQE", "text": "Ты рилзь бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0Jl6DpJzAeUylvaVDkIbmoWSPDCMAACPhsAAnLwuEvUCYaRlfs--jQE", "text": "Ти псехованний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0Rl6DqGPA3M1MpX5nnFMDGZVoZkXgACuz0AApvdoEiERtMvlGAEQzQE", "text": "Ти плинцесса бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0Zl6DqxYDnDD157DhoyPrDE-BK5DgAC_TcAApZyqUjzaavN9bFZiTQE", "text": "Ти спа бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0hl6DrOYv05GE5zVjwhcoyYJsVwKwACqz0AAkwCoUhYZ0an8S3F4jQE", "text": "Ти хорни бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0pl6Dr_GRqLwSkVQ3L7mqzrMvTsPAACxDoAAohnoUhEqFDtTJmB4TQE", "text": "Ти неплабиваемий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn0xl6Dsze1yEDMrfFtVSoAeFXsosbwAClyYAAnRwuUuX-TKXWW-IrjQE", "text": "Ти филасафский бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn05l6DtkkLrdqeKsRUnjKR3csiU7DgACmCUAApZwuUvBb_Lv7Jb-QTQE", "text": "Ти рабосий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn1Jl6Du2pOOWLC_pMKvGV_CW-fxOVwACdhQAAp8q8Etvol-HKHx8azQE", "text": "Ти сазелцаюсий бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELn2Fl6EA3qBev2bYkVpwwhtB1bfjiMgACWDcAAru6qEkLfAABgQ7FnHw0BA", "text": "Ти мине пофег на всехъ бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn2Nl6ECDsfNG3O8VeSbIYIPEwc7wkwACGDUAAtNuqUlRFDPtjkyCfzQE", "text": "Ти айти бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn2Vl6ECq9_vpRM61G7FnXZzIDVABHAACRDgAAgcQoUllQJYK7pyERzQE", "text": "Ти слядький милый бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn2ll6EDGaq5EB7wz9tqaZ2D7-5BFLAACNTYAAmk6qEmXssAkILvthjQE", "text": "Ти музикальний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn21l6EDc1PKz8Y5c-Hwbxm5LMo5G6AACCDcAAkd4oEktKSqrVVy13zQE", "text": "Ти гулена бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn29l6EER4rXnQBIu48rCCp7GPHtHhAAC9T4AAl_pqEnAHhVwh3HSSjQE", "text": "Ти руливой бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn3Fl6EE4T6TgwgUlTrNDa8oBZGYOzwACfj4AAi-IqEnq_DObjGStZDQE", "text": "Ти на чилли бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELn3Nl6EFchbE6dy3VpgirUJWiOMCKWgAC4TkAAnpPqUmXswdrOEMnzzQE", "text": "Ти бахатый бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn3Vl6EGMPvM4iuZEPrcN_FHjFLIFMgAC0TwAArzMkElFfoYrr5_ONzQE", "text": "Ти спакойний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn3tl6EH9MB8nXK4IueIjB2OTiHJqfQACqRgAAmsw4EuNUYzNXVIytDQE", "text": "Ти вайбовий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn31l6EIrg1iOTZZ0KXpTbuW93ATsSwACGToAAr0boUgYx9I7K8vspjQE", "text": "Ти аглиссивний бибизян!"},
   {"sticker_id": "CAACAgIAAxkBAAELn39l6EJN_3KoPqsypMWvkBLL15KxQwACpikAAkxguUviIsERX6N2HzQE", "text": "Ти уболка бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn4Fl6EJk6xEKt55mE3K0EDMTIbOWbwAChzQAAilx-EuDeKVjPIKtuzQE", "text": "Ти рамантичниий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELn4Nl6EL-l0Cp9A8rSKEq3HgPlSkKnwACOjUAAnBegUiUGQHBPXcCcTQE", "text": "Ти глупий бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELst1l81i0PIDzPiMcX-rhmO-2VY0orAACnxUAAuwBaEqQdd-iXXRhljQE", "text": "Ти нидавольный бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELst9l81j9cBtjRvUjo6z3GgZXh2m14QAClh0AAkOecUrpF7bg50K_STQE", "text": "Ти дзень бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsuFl81klHW2JQd6tdY1KWdjeOlbkpAACJz0AAtVLsEprw65XjdPaXzQE", "text": "Ти шапаголик бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsuNl81lPolbkcrEPMoKnpNygYuOzIQAC2xwAAiZ3YEqnvDS3MtXm6jQE", "text": "Ти спин ми ряундь ряундь беби ряундь ряундь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsuVl81nDrDVkUh-TJ6fEElOK02VD1gACdhgAAmTrcUorDzUcFen_GzQE", "text": "Ти Елжань встявая бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsudl81nYotppoTanTJ-5M7ngwVla2gACpz8AArfRUUruJ-KkfbG7-DQE", "text": "Ти ранняе утла встявака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsull81n0Fn_ZHUjmcjjgJ-sQ2K2dQwACaz8AAlWcoEr9Ec6G13g0GTQE", "text": "Ти бибизян-аклобат"},
   {"sticker_id": "CAACAgIAAxkBAAELsutl81oVNEEZjiEiZicsI0lTt4i5ewACJzwAAoQxqUryMBwvQ3EXgDQE", "text": "Ти випивака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsu1l81opGRLLLIs8acy3wkiOjbhSSQAC7SgAAp8H2Ejexxz-UFB8dDQE", "text": "Ти банька-палилка бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsu9l81pHSXiSCHgmsJMoN9Byfm0w0wAC4ygAAn-t2Egjl7KgjfPkKDQE", "text": "Ти вэйк зе фак ап самулай бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsvFl81qIjs3Xf8CDqqByxqCDJD8K8AACfhsAAuW6cEr3VsXJ6IBU4DQE", "text": "Ти сибастьян бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsvNl81rJcCR0P5wISCgE-FGQRJcNSwACbRkAAgftaEoGOoSKQaZHZjQE", "text": "Ти даложний бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELsvVl81tJEnQzLDUSdKjJYouWXy7FKAACfBYAAtROcUp99hZvJkc6pzQE", "text": "Ти на скусьном званке бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELsvdl81tvBw8TAqP2DwpHYDrmVOkcPwACCSMAAlKgCUvHEehZomsC0zQE", "text": "Ти пиликурьный бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAELsvll81u_b4EgMuEFGZWiYMrU2G9eNwAC1xgAAhpiaErncd_3ispHIjQE", "text": "Ти длама куин бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsvtl81vh6TWECNMEA6c4JB4ZEaTDBAAC3CAAAgdFeUqf5yrKjQjfPTQE", "text": "Ти в шоки от всиво бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELsv1l81z17Wz45Dzj9J6ghbODNOxJZgACARkAAteFaUruQolcdGw7LDQE", "text": "Ти сигма мейль бибизян (зябудь иё...)"},
   {"sticker_id": "CAACAgIAAxkBAAELsv9l810hgZn-xTyWRWt2sr66T_ocWAACEBgAArTqaUrk2u9Cp6hvfzQE", "text": "Ти балдежь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELswNl811GBdRPiQGbSp2A9gRcBWjB5wACKy4AAh-AkUuSlw7WgNI9ajQE", "text": "Ти фсех усатаю бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAELswVl812HTfHZvlAR2hjXvHSIXxewlQAC-S4AAnVBiUumbYTYv2-pYzQE", "text": "Ти мега умниииий бибизян!"},
   {"sticker_id": "CAACAgIAAxkBAAELswll812kfE2xqD7jhSo_5xXUZYRENwACXhoAAv0hcUqRJMR4wyEPrTQE", "text": "Ти бальной бибизян. Виздалавливай!"},
   {"sticker_id": "AACAgIAAxkBAAELz0JmBZ8Xs1jdHaulq_B-E9MPZpPdSwAC3TYAAlKugUis-2plWg0dszQE", "text": "Ти ни твёй диень бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2FdmDuQiKmPiYukAAcqfF2EJOh-SzjsAAi1DAAIKyTBIRSOt3H1JIjY0BA", "text": "Ти пасти пилигалель бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2FlmDuRBKA0iAAFMhLV2cSMNClGFm6AAAj5JAAISuzhIvxzTdGZWLSE0BA", "text": "Ти тякой клёун бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2FtmDuRPwzrY69bYvRKHCbx5RL9sFAACiDkAAsSM8EttkHu6xGPRkDQE", "text": "Ти сьто та натвалил бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2F1mDuRojdkP1Ff-6Rc2KFFSIC4N1wACHj8AAkIcOEgSr3z7vwABJU80BA", "text": "Ти винаватий бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2F9mDuSvS2-I_ox9j0hC-Dt3BeIkewAC8UgAAh-sOUj9VBbSMifrPzQE", "text": "Ти клюбний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2GFmDuS7JVnRREMeJUcLg_8LvWfJwAACOkcAAu1cMUjbavTHXXBRuTQE", "text": "Ти насьной поедака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2G1mDuYvRjRGW865BkcDHPpV3aEH0wACCU8AAv0-OUi0dANZez_9_jQE", "text": "Ти азальнёй бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2G9mDuY1FCyCX5O1FB74OyRbtJdR3QAC3kMAAogkOEhV7Pqxzumo1DQE", "text": "Ти бай-бай бибизян 🤫🧏🏻"},
   {"sticker_id": "CAACAgIAAxkBAAEL2HFmDuY6hrSqH7I8bic5HWx_WE5EvQAC90MAApYtOEgtZxBXoBMiMDQE", "text": "Ти скуф бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL2HNmDuZHqmi30R53p4AUoDMuIV2G9QACHUgAAj0EOEh-UE-AZJB--zQE", "text": "Ти плисел с пилылыва бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-2VmKSK0ovXLk2a9dWBmK7oxAAH68BYAAoZGAAICfQhJWPxSCLTsGok0BA", "text": "Ти агланисена годьний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-2dmKSK8WKQwc7zz3w86-T2Sknt0ugACCTQAAnS0qUhnIMpX2xGD8jQE", "text": "Ти сациафоп бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-2lmKSLElaRn_txJ2f5Zpi5Xxn-6PAACmEYAAgNfOEhxSM4rdtoNMjQE", "text": "Ти плавацилуюсий бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-2tmKSLKRussSdYHp_krvcHTYjEvrwACqz0AAk4uqEmuJ1z6JwYN9zQE", "text": "Ти хюдеюсий зоз бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-21mKSLZhwbJZZbbsqkX87zrYsaACQACYjMAAiKSoUnOI1Z_Xvz4SDQE", "text": "Ти хосис унистозить фсех бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-29mKSLf2Lz4b8dJBECfewaQrgeiFQACLhQAAgVk8Et1Ekd5Y-WSLTQE", "text": "Ти осинь хосись дамой бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-3FmKSLldWxtc4VtW-QRUxrHcWKruQACSRcAAhRq6UtnlJpA0KKLDTQE", "text": "Ти кайфусьний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-3NmKSLsNNSrxseHn80vXy_Lb2sRJQACnz8AAqqLmElrk7FNk63ngzQE", "text": "Ти внесьне висёлий но внутли глусний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-3VmKSL1GL8yAf2Rw8rkEqmlhD58xQACtjUAAujLmEl7oahUhs1KyTQE", "text": "Ти усталь слусать блед бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-3dmKSMSTg0alpdI9g4E2I0kwUHrAQACWTYAAi0_mEkqfNrf3AYn1DQE", "text": "Ти сматлящий в дущу бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEL-3lmKSMex1Jf98WmW6Sqhbs8uyefqgACejkAAlEjqUlXNa_C9bjsIzQE", "text": "Ти балдееюсий с длугом бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjU1mpVY5pBK7Tprg1uyLDMIemGKwNwACWUgAAs_D-Em6kQpsVlQ4jDUE", "text": "Ти всегда на стлаже бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjU9mpVZ7LbkR48K_BEOw-nh1UiZiugACYjIAAv5ZwEqfdTpzh-3DPDUE", "text": "Ти остлий казыёлек бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVFmpVaJY2OKw8Rg5jouu2f0u51aEAACFEoAAk3J-Ul_h3C7LuHsqDUE", "text": "Ти сами умни бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVNmpVaYrpjDzYCIS3Hr71LQKLxpFwAC9zEAAjzbCEtOt4Tsl4acyTUE", "text": "Ти сто-то задюмаль бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVVmpVap8HcRj2l12-Se7VpsIm56-wACdi4AAiMUCEtAXE9j4kLBnzUE", "text": "Ти поньски пон бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVdmpVa4h3sTYVz0zM_gYwO5vDisrgACMDMAAvIpCEuOKbciXogFgjUE", "text": "Ти вкусня.тоська бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVlmpVbQC7p4Er7juPS7eJoMT7ydOAACskwAAtN3AUpRV3pKSd0a1DUE", "text": "Ти накулиний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjVtmpVcPX_Cr1nBH7zLOiDULeTY8QAACwCoAAjyGEUvMGEnY1r7dfDUE", "text": "Ти пладал бальсой банан бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjV1mpVcdJDgfph1ZRE3igg_pFdKdAAPcSQACN9oBSl94Sn0OTtUsNQQ", "text": "Ти инглис tea-taim бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjV9mpVcscKuVhJflto0oLugAAVP6wcUAAggqAAKsyhBL9pu6XWmLo2g1BA", "text": "Ти закязивать пакусать бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWFmpVdJ6epQ6y7ASgABu-hZU6miR4oAAlZJAAL6LgFKhEIquuehdVg1BA", "text": "Ти Геньдяльфь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWNmpVeEkbdW9Ow0fLWNefK3-WyiOwACeCQAAhQJEEvIWFpUoWtQDzUE", "text": "Ти не тлогайти миня бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWVmpVesjonF5Zhm9uXyFArMyutoPQACkCgAAnIrEUtzI1mc7lT-3TUE", "text": "Ти батя на дасе бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWdmpVe9SDBI3IxXNZYLqA7XZw7z-wACwSoAAt7vEEurdc4yWLhq6zUE", "text": "Ти отьпуськ бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWlmpVfJPzJ_p1MnRqE__Lsl14IHGgACaTMAAvHNCEtD3zLf5Iu92zUE", "text": "Ти абнимака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjWtmpVfXQBUsj3oKzwJoHUTl0UuITAACrk8AAuMLAAFKpEDl5dBPlOI1BA", "text": "Ти тяксист на вакзале бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjW1mpVft7zI6W9DiQFbr0unX-SwfTQACGk0AAshv-EkwMqsURHLN6DUE", "text": "Ти слусаис скусный бубнез бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXFmpVhVT5t1qiyZA2PhLfwYIbYtzwACBUcAAtGwAAFKEs1CriFJyFQ1BA", "text": "Ти ниискилини улибака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjW9mpVhFPFnc8cmmOeNHbIOfBccpeAACnkYAAl6R-En9IpBgZ21EgzUE", "text": "Ти падгатоьвка к ИГЕ бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXNmpVhiFCMlJqf6jeGIhxEB7kwsXgACaDAAAnA3wUpgBk3RoavFfDUE", "text": "Ти гудь дзобь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXVmpVh7cO_S01D2EcfCAxkPUzwcjAACYUcAAs0W-EmC_oHKcI0xSTUE", "text": "Ти балбелсоп бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXdmpViKxytAXErv-IFo8_3Bu5fMJwACSjMAAqCHQUr9RnjYMl8zoDUE", "text": "Ти хализматисний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXlmpViWMJV6qpazWOypGHwBmgT3SAACjUoAAiZwAAFKr3p2_sUaAd81BA", "text": "Ти тлудавои бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjXtmpVisc4tUWteCc5-bDyIgAUli_QACj0gAAljsAAFKr2P_MOU7iEY1BA", "text": "Ти бальсая зальплята бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjX1mpVi5hk4D25RenSMez_YQiQ4iYgACu0oAAuViAUporXiIscnKaDUE", "text": "Ти малтыскинь тлуд бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjX9mpVjKpTIC4vzGlAn14Mq3m4p7mwACAzUAAsAkQEq87n9FDPYQKDUE", "text": "Ти геймерь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYFmpVjg8GWzlMCpRVSBwnQq0jfH-gACUTkAAqlYQUqoxgLtm6n2KjUE", "text": "Ти стисньяська бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYNmpVjvbm161Mn3hUlJVuZ_z-BvsgACmE4AAux5-ElATl0RCh_KuzUE", "text": "Ти «засемь мине телезка» бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYVmpVj_qhPvnGT22k8MlIxZUEZEDQACgUkAAmeTAAFKiTGBrh2LI0g1BA", "text": "Ти йазык зестов бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYdmpVkPQRfgM2h8QZxY6kDQwB6zbgACH1EAApK0AUokFnB44EQEkzUE", "text": "Ти клипто бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYlmpVkdFmBP4_elwjT9v-5cczF8dQACsEYAAlGE-UkC2udpQi90HzUE", "text": "Ти здуля бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjYtmpVlM9m-ONAyyiaMJYEW2OEAzVgACg0oAAnGo6UmYQQyAPGRdIzUE", "text": "Ти «как дила па задасям?» бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjY1mpVlaUKlE0KwGwG86SR7ul1GUJAAC5UsAAl3s8UmhNwfwN2WJ6TUE", "text": "Ти наканес-та отдих бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjY9mpVln7TAUJurCBoQNj4BtaqAyGwAClTAAAj_LQUpLrXyxMYsELzUE", "text": "Ти флантальний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZFmpVl6LtqR5NAZFGnMu-rBKOXgOAACETMAAotXQUoZBJm9bRUf8zUE", "text": "Ти давис писеходав бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZNmpVmHsx6THfLQOTEgdDVdHyaNUgACL0IAAnQ7SUlmc4jhI7xlLTUE", "text": "Ти накасячиль бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZVmpVme0IMhrINBk8HzASXw3_f3jwACzFgAAuG36ElN7WvH1tKuEDUE", "text": "Ти налцисс бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZdmpVmqtwZuhF8bROjjg7uYAeTRXAAC80MAAqa_SEmGlr6fnkQR2TUE", "text": "Ти малинькая залпьлата бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZlmpVniq-IKR-KRIf9FxbG8gvhiIAACQ1IAAhAI6Ulx0wY3CNYIcTUE", "text": "Ти нивысипака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZtmpVnzkRmIEgII89cY3iaWZrB6LgAC7zcAAqcKQUpcfwIjd-UiRjUE", "text": "Ти саблазьняка бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZ1mpVoB_hx-m7VrrglbIghJkWXGTwACVTQAAhcIQUp-FAE2Ylt4MDUE", "text": "Ти маляньки памосник бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjZ9mpVoWFfrFHWR7WjOyE0_ijyFTtgAC1koAAkI16ElcIlClFa49rjUE", "text": "Ти убиваес селдце бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjaFmpVomwzkjm8njYy07N4oEiDV3KAACHFQAAs9G6En9ApRrFxU_njUE", "text": "Ти тязёли ден бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjaNmpVoySgtXdNw8a7wdD5VBel7v9wACP0oAAhpP8El-knCaUNCtIDUE", "text": "Ти атклюсили галясю водю бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjaVmpVqHOd3TQ4IGeaE37sLwH-Ua3AACvEoAApMK-EmYr3XuDO3a0DUE", "text": "Ти маникюльни бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjalmpV0mr3U1rnjN9omLKgHFAAGCi0EAAsVRAAK2xuhJBRb-Uxq7QC81BA", "text": "Ти дяставака бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMja1mpV1Gjjygfk7XmqzclRdz1oO66AACcjIAAg8jQEqKzEg0xE7VhzUE", "text": "Ти стилака бибизьян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjatmpV04GTfVwgo5uCaBQ8kEpZysWgACqy8AAjpsQUoG1MwAAYoScow1BA", "text": "Ти ривью кёда диелать бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMja9mpV1Zu1lJAXgBBFk8lgJqP29-gwAC5jYAAgIAAUFKZSTR8R_Of3g1BA", "text": "Ти камандная лабота бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjbFmpV2IIR15CCMZNdePQzufMDW6IwACCTgAAtCaQUqASK14cPIM1jUE", "text": "Ти WTF бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjbNmpV2w0CB4-3KFmixBXppdHMU37QACIUoAAq3r-UnfFE7sqO8KvTUE", "text": "Ти бухалтил бибизьян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjbVmpV3UI7LqTg3-lFMFLNCoLltzrAACU0kAApgZ-UnduyRGILOORzUE", "text": "Ти вписка с блатками бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjbdmpV3p0ZHr6pyWvBqNbUIgRE8-pQAC2jkAAgej8UmnSGBDRbiBTzUE", "text": "Ти сухамятька бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjblmpV4sd7XM4c-WixyueLc9SRi2AgACXDQAArsTQEqkDEB6ymt_jTUE", "text": "Ти втикаесь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjbtmpV6EfQfguSGEbSwPuNxGAnu2fwAC4EkAAicG-ElCybFtJlfTATUE", "text": "Ти Людовиго Эйноди бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjb1mpV7Fa_QdwVlQfTNc1RaA1VLR1AACazsAAgN28Em1CfwRmVBBqjUE", "text": "Ти писевое ластлойство бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMjb9mpV8U_TqyqkGb3vMbcS9m5Xw25AACLUkAAkztAUpc90ETNzIO8TUE", "text": "Ти атключили лифт бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjcFmpV9k9NKYp6TMbiyArkixYDvfEgACXjsAAmCzQUp8m8NWySkmEjUE", "text": "Ти суес свои нось ни в сваи дила бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjcNmpV_PNO8JXT_yHEGoIfVAoxPL3QACgUoAAnd3-UmIEYhjhxwPhzUE", "text": "Ти пранкирь бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMjcVmpWARHWAw3BI0ZTh06a3IFDhclwAC408AArGC-UkCznxHkCA-ZDUE", "text": "Ти гусси плада бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMjclmpWC6btuDYw8Wt9HHupz3X8N2PwAC_i8AApWt8EkrSp24jSPwDDUE", "text": "Ти мамина ладость бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMjctmpWEmHFRBKF3ycdnAUgxrXLxg9gACzzMAAoan8Em96RH8zJcnoDUE", "text": "Ти пупсек бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqVNmwJc4Ufqk619yEF2BBgUvPvfDNQAC8UsAAq6--EncXn5A4RXUQTUE", "text": "Ти тливозний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqVVmwJdEUiJuN8kmJV4N7aseAnCPLAACTkoAAtuPAAFK_o4ai_LRWoo1BA", "text": "Ти снова кулю мама сновяя бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqVdmwJdNGTiB6Iji9mKIeG1PoUN1EgACFzcAAs_G8ElMNLIy9cIi5jUE", "text": "Ти длазнилка бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqVlmwJdalhX7ARGmKkkpNgmZgsJ8aAACd0YAAjYP-El7_77L5Kxw3zUE", "text": "Ти либалка в 5 утла бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqVtmwJdl3ocy1agpyinGrGwzAAG8q0sAAj5IAAKGOgFKjJPZAzDuUwc1BA", "text": "Ти памосник бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqV1mwJd7CM_7I-8IJNoP5hYkWxWL5gACFS8AApiyWErdQJUcQTl2ejUE", "text": "Ти нивлотик бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqV9mwJeFEKH7dru8ycICwAVgeygnVAACRkoAAhSQAUqaoKUrgKYDhjUE", "text": "Ти пивазавл бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMqWFmwJeRdSQLkyppJH0ZhqwRIazkNwACU1AAAksYAUpbzIqivZ3ICjUE", "text": "Ти сямо ачалаванье бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqWNmwJeclQL-Ycy-s-SwqZUcQ1wHgwACjEgAAh-V-UlGNKbx2bh5FjUE", "text": "Ти стильни модни бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqWVmwJewpgPmid3MJxXqnWIQ9XPOmwACFkkAAhMP-Unj0fi6_srlezUE", "text": "Ти ни панимаис ста плаисходит бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqWdmwJe7eaLZtQafiGK2Qgr5Ummp7wACGEoAAq3UAAFKlFcZi-HNmXo1BA", "text": "Ти се рямсы папутал бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMqWlmwJfHH8oZ75i08QU9MZgDxG8WxAACHkUAAtiE-Umq8T93TntNRTUE", "text": "Ти емосиональна вигалел бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMqWtmwJfxBde47g6e8sMf3QpnS822ZQAClU4AAh7g-UmGjaR3LIPq2zUE", "text": "Ти эспебэ бибизян "},
   {"sticker_id": "CAACAgIAAxkBAAEMqW1mwJf-mrEoFEcRIuI0iy3mpgq0NAACsjsAAjNo8Ul56KjTsJaA-DUE", "text": "Ти а есле найду бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqW9mwJgYM4_ONC8Pv_vPmQ4pavPZzwACjzYAAozM8Ekdap6tOo2xQTUE", "text": "Ти 360 гладусов нёускоуп бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqXRmwJhI-4ji2rOUvsWlbXEnbnoRoQACajoAAtLU8Ek8tcsorppLDzUE", "text": "Ти славянски бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqXZmwJhkR2lfi1_RfUBzlWk9CCwtNwACxEUAAicI-ElgmIaxx-qwVDUE", "text": "Ти стота плинуныль бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqXhmwJiFp4twF6dQxg5cSpDbc2gOmwACfC0AAoFswEqN6wNftxnXXDUE", "text": "Ти щлепа бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqXpmwJidc0vhPUidvEE5FZWDGiA2FgACiS0AAkjswErGoSRJrRm_dDUE", "text": "Ти доньзуан бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqXxmwJiwfGReEVpf0mlXWB2_1JOnKAACeT4AAiwo-Enktzcs44rHEjUE", "text": "Ти плапустил дедляйн бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqX5mwJjusDnHvgvvUay3jffdkyNncwACx0IAApehAAFKlqBjSd5fs2Y1BA", "text": "Ти лукавадитель бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYBmwJj55XqeVk4bnUmQKnMgTlUCHwACIC8AAjYJwEpuNVjhpKWA3DUE", "text": "Ти лаксели лайф бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYJmwJkigeGVUfpUbwf0gKPv6nD0sAACJFcAAqDfAUrbCFqFbjGXijUE", "text": "Ти ЧээСВее бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYZmwJk32SuiFvvAMa9xk4veZY9qvwAC0ikAAtgiwUq8tNLaMjQ5EjUE", "text": "Ти йа в отпуски бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYhmwJlJ8rhaK8Ru0FXXtf5GW61P3wACBCoAAgMswUrEMvdQylQ2ozUE", "text": "Ти интелнет зависимый бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYpmwJlgAwcBdZ2bxp-xg62xhyQBrwAC2kUAApxU-ElppNWWuF0QkDUE", "text": "Ти СДВиГэ бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqYxmwJl8gMZdkHwgPkL_72Euc6fVlQACIk4AA7H4SaETQATtT4b7NQQ", "text": "Ти чайлдфли бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqY5mwJmRIEi-ASQcR7HPQUDimxQgPQAC0kwAAv1jAUrIu98iewsvPDUE", "text": "Ти суси на нось бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZBmwJmnM8vtV8ebQfYYTX1W9LcrRgACFEcAAu-G-EmvsMOthZv1XDUE", "text": "Ти сделяй мине класиву фоткю бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZJmwJnXflNGwwuMkxv6ZgRYKTVGVwACyUcAAl0O-UkNlgoEMZBN7zUE", "text": "Ти тяктильни бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZRmwJnwzpFDMXAW0gQv316wXPvc2wACPTkAAqsUsUn63hqO6zkrYDUE", "text": "Ти на пазитивсике бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZZmwJoDdQUhnLwGf0qyunHztVwmTAACwDUAAtV1qEkyAkThsUfquTUE", "text": "Ти папина ладость бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZhmwJolihOsHtduFXIwM1PtK_jZcAACvjcAAtBDsEkpfnrJhbo-KDUE", "text": "Ти блек стал бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZpmwJo74IKrQ4nsBQXMmatV77jNRQACnD4AAuHVqUlVrrWg9_EAAdg1BA", "text": "Ти детская тлавма бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZxmwJpK7lW08WnuyrXxAgjLKMrnYwAC_TwAAlCAqUk7yn0mz0tI9jUE", "text": "Ти папин блодяга мамин симпотяга бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqZ5mwJpk1Iw0UkNppMnag2EXoG1rLQACGkkAA1X4SfQXZNexVZ05NQQ", "text": "Ти любись массажик бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqaBmwJptYYvw60AilaBpRTlHLdV5twAC2kQAAnJu-Em6F-zE7FTJXzUE", "text": "Ти есть в калмане пачка сигалет бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqaJmwJqGoQX7mV2_x-SErmYRX_GGPgAC5DQAAiJk8UmRHWDtJoFb8jUE", "text": "Ти не затикаюсийся бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqaRmwJqcyILCQ5E2yVgAARsqsPHMOekAAk1HAAJZtvlJ6L-f4FsHeaE1BA", "text": "Ти мини скуф бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqaZmwJqy2U-vaBZiva60KyK5U023_gACpk0AAucOAAFKeOi2OtiTTwY1BA", "text": "Ти здес нових бибизянов бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqahmwJrAEXhOWjDQBGV0pQj0GKifGwACsksAArI4AAFK127DTSPugC41BA", "text": "Ти полуносник бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqapmwJrQ97tKxGVl5FlZpkDHmxqkyAACIEoAAtA3-UlFPBQe-wIKyTUE", "text": "Ти дневной сонь бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAEMqaxmwJuu4ceu8cPv_PMR_fpcJbfdOQAC6kYAAicS-Ukg55_m8PU9RjUE", "text": "Ти волкь с волл стлит бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBHpnHPqNw8rATKRc3_2a75KBPMajmwACL0wAAmn76EhOQ2g2XK36oTYE", "text": "Ти нада падкачаца бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBHxnHPq0B5wnH0sxAo7Bob547CysmQACOVEAAmKjqEn9jmj-RqJflzYE", "text": "Ти плазднисний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBH5nHPrMkZZT6QvEXOfBGY-Fag4cKQACp0wAAp-FoUmFlHcr_VZK1zYE", "text": "Ти мине нузни снимки силавека-бибизяна бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBIdnHP-2jNp_cP6otnJItGhp9DobgAACQjwAAkqzqEmZ6d6nSZQDGzYE", "text": "Ти бизбилетьник бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBIlnHP_MLX7EvOk5CyVKpISlQo3J3QACakEAAkLbqUkGcsEH3GKQoTYE", "text": "Ти в мелу упитяний бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBItnHP_hDqTkU1-p1Z3IDGUKsJp9ZAACdjgAArgzqEkiH0zdNbFZUjYE", "text": "Ти сильна клутой бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBI1nHP_rKaiwHoigFk8YNYhVLZ_zyAACyzcAAsqLqUnHG-68BSTTHDYE", "text": "Ти милий када злёй бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBI9nHP_8Fz5et0Mm7uaH08CtmHA5zQACXUcAAv_g-EnD3mpmvTms5zYE", "text": "Ти ни любис дилиться бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJFnHQABApztobca_YACSYUZWix0uGcAAnE6AAL866lJVQgFUgtWUwc2BA", "text": "Ти внесне глустный, но внутли виселий бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJNnHQABFmpXvp1wq43UNGhdCrQ-_LAAAiJIAAIqngABSh6sdcDWQK3_NgQ", "text": "Ти впаль в дество бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJVnHQABJWSRkKBK1Ihm0VS3jGj3gwUAAtw6AAK8-rBJNdORd05PMcU2BA", "text": "Ти питаеса наладеть рижим сня бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJdnHQABPROqLpXcwzVwYjKO84IR68MAAu1IAAJecwABSk3031y3ZvQYNgQ", "text": "Ти слисис на лаботе свае имя бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJlnHQABQwuGH-yO2Jfg_dd07dqQVV4AAgM7AAL_WahJB5Wv1IoBl-42BA", "text": "Ти калселинг бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJtnHQABU8hIqZEioOx7Ify7gPtRMbcAAiU7AAI8b6lJI7awqr0QctI2BA", "text": "Ти матасиклист бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJ1nHQABWoH38wiZSTuks7mt2i3iXGcAAiM6AAIO2LFJk0MNfiY9e7M2BA", "text": "Ти пазевулькин бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBJ9nHQABZbmYMNVta8n5nDV-K9IFSP4AApBAAAKz3alJfEWBPvr6J082BA", "text": "Ти в полнам щоке бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKFnHQABbvSVW8Eq_DGNklBgf16K8kQAAtA4AAJLFqhJ4M_hy5KYUpA2BA", "text": "Ти пласнулся в 6 утла под мелзкий будильнек бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKNnHQABdvvJtCLV8Dt8HaiuYT3Y0YEAAlZLAAKejwFKCjV4WYhV1r02BA", "text": "Ти на дяче бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKVnHQABgJliOLGE7vl6_A9Gy4KjVDAAAm1CAALsa6lJN34QLWf7DJg2BA", "text": "Ти иглаес в 1000й лаз wanderwoll длузьям бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKdnHQABjS1s5IQxLi1F8CKa2aFUO0sAAoFMAALMVQABSlhO2Ksn6529NgQ", "text": "Ти без лисных гланиц бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKlnHQABlaFCUXwzXp2m1r8-lIFyApIAAnU2AAItyalJvmlB3kogWXg2BA", "text": "Ти делаись селфи бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBKtnHQABnkjSB2GytTseF0BElg1V7swAAmZNAAJ54fhJw_YsSpGd2oQ2BA", "text": "Ти пасти завизал бибизян"},
   {"sticker_id": "CAACAgIAAxkBAAENBK1nHQABsX52qR-HqQpxyI41tE4AAQYEAAITUgACAqkBSgmO4X9a3IBNNgQ", "text": "Ти любис ягадки бибизян"}
]